### ISSUE TITLE
python httpserver_imagesearch.py err

### ISSUE THREAD

**Issue by fanyoujian** [guoxiaolu/image_search#1]
python httpserver_imagesearch.py
Traceback (most recent call last):
  File "httpserver_imagesearch.py", line 7, in <module>
    from image_search.elasticsearch_driver import SignatureES
  File "D:\tf\image_search-master\image_search\elasticsearch_driver.py", line 1, in <module>
    from .signature_database_base import SignatureDatabaseBase
  File "D:\tf\image_search-master\image_search\signature_database_base.py", line 1, in <module>
    from image_search.image_signature import ImageSignature
  File "D:\tf\image_search-master\image_search\image_signature.py", line 3, in <module>
    from scipy.misc import imresize
ImportError: cannot import name 'imresize'

**Comment by guoxiaolu** [comment]
scipy is not installed or scipy version is not the latest

**Comment by fanyoujian** [comment]
hello ,which you python version? I am is python3.5




------------------ 原始邮件 ------------------
发件人: "shiyuan"<notifications@github.com>;
发送时间: 2019年6月14日(星期五) 下午4:09
收件人: "guoxiaolu/image_search"<image_search@noreply.github.com>;
抄送: "慢半拍"<1620683945@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [guoxiaolu/image_search] python httpserver_imagesearch.py err(#1)




scipy is not installed or scipy version is not the latest

**Comment by guoxiaolu** [comment]
python2.7, this framework is not updated, maybe facebook-faiss is better, elastic-search is too slow when image search, especially when the images pool is too large. so I don't suggest you to use this project.
